config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home', as: "homepage"
  get 'static_pages/about', as: "aboutpage"
	root 'static_pages#home'
  resources :messages
  resources :campaigns
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name,  presence: true, length: { maximum: 30 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
  	validates :email, presence: true, length: { maximum: 30 },
                    format: { with: VALID_EMAIL_REGEX }
   VALID_NUM_REGEX = /\A\d*\z/
   validates :phone_number, presence: true, length: { maximum: 16 },
   				format: { with: VALID_NUM_REGEX }
   	validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < InheritedResources::Base
 
	def index
		@campaigns = Campaign.all

	end

	def show
		@campaign = Campaign.find(params[:id])
	end

  private

    def campaign_params
      params.require(:campaign).permit(:title, :content, :start_date, :end_date, :photo)
    end

end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		if @message.valid?
			@message.save
			flash[:success] = "Your message has been successfully sent, we will get back to you as soon as possible"
			redirect_to new_message_path
		else
			render "messages/new"
		end
	end 

  private

    def message_params
      params.require(:message).permit(:name, :email, :phone_number, :message)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@campaigns = Campaign.all
  end

  def about
  	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/campaigns/index.html.erb
<%= render "layouts/navbar" %>
<div class="container mt-5">
  <section id="campaign" class="py-5">
    <h2 class="text-center">All campaigns</h2>
    <div class="row">
      <% @campaigns.each do |campaign| %>
      <div class="col-9 col-sm-6 col-lg-4 mx-auto my-4">
        <div class="card">
          <%= link_to image_tag(campaign.photo, class: "card-img-top", alt: "picture"), campaign %>
          <div class="card-body">
            <div class="card-title">
              <h3 class="text-capitalize"><%= campaign.title %></h3>
              <h6>from <%= campaign.end_date.to_date.to_formatted_s :long_ordinal %> to the <%= campaign.end_date.to_date.to_formatted_s :long_ordinal %></h6>
            </div>
            <h4 class="primary-color text-capitalize"><%= truncate(campaign.content, :length => 50) %></h4>
          </div>
          <div class="card-footer team-icons d-flex justify-content-between">
            <a href=""><i class="fab fa-facebook fa-2x"></i></a>
            <%= link_to "Read More", campaign, class: "see-more-link h4" %>
            
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/campaigns/show.html.erb
<%= render "layouts/navbar" %>
<div class="container mt-5">
	<div class="row mt-5">
		<div class="col-md-8 mx-auto mt-5">
			<h2 class="text-center mt-5 pb-5"><%= @campaign.title %></h2>
			<p class="campaign-show-paragraph h4 pb-5 text-center">
				<%= image_tag(@campaign.photo, class: "campaign-show-photo pb-5") %><br>
				<%= @campaign.content %>
			</p>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer-container-fluid" class="">
  <footer id="footer-div" class="d-flex justify-content-center">
    <div  class="row">
      <div class="col-md-12 text-center">
        <a href=""><i class="fab fa-facebook fa-2x"></i></a>
        <a class="h2 pl-5" href="">icon</a>
      </div>
      <div class="col-md-12">
        <div class="footer-link-div text-center pt-3">
          <ul class="list-inline">
            <li class="list-inline-item h4 text-white">item one</li>
            <li class="list-inline-item h4 text-white">item two</li>
            <li class="list-inline-item h4 text-white">item three</li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav id="landing-page">

	<!-- Navigation -->
		<div class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" >
			<h1><%= link_to "Logo image", root_path, class: "navbar-brand" %></h1>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
		    <span class="navbar-toggler-icon"></span>
		  </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
		  	<ul class="navbar-nav ml-auto">
		  		<li class="nav-item">
		  			<%= link_to "Home", root_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "Campaigns", campaigns_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "About us", aboutpage_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "Contact", new_message_path, class: "nav-link" %>
		  		</li>
		  	</ul>
		  </div>
		</div>
	<!-- End Navigation-->

	<!-- Start landing page section-->
    <div class="landing">
        <div class="home-wrap">
            <div class="home-inner" style="height: 50rem">

            </div>
        </div>
    </div>

    <div class="caption text-center">
        <h1 class="">Achieve Your Dreams Foundatioin</h1>
        <h4>Making it work for good<span>...........</span></h4>
        <a class="btn btn-outline-light btn-lg mt-5" href="#courses">Get Started</a>
    </div>
	<!-- End Landing page section-->
</nav>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" >
			<h1><%= link_to "Logo image", root_path, class: "navbar-brand" %></h1>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
		    <span class="navbar-toggler-icon"></span>
		  </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
		  	<ul class="navbar-nav ml-auto">
		  		<li class="nav-item">
		  			<%= link_to "Home", root_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "Campaigns", campaigns_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "About us", aboutpage_path, class: "nav-link" %>
		  		</li>
		  		<li class="nav-item">
		  			<%= link_to "Contact", new_message_path, class: "nav-link" %>
		  		</li>
		  	</ul>
		  </div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AchieveYourDream</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.name %></td>
        <td><%= message.email %></td>
        <td><%= message.phone_number %></td>
        <td><%= message.message %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= render "layouts/navbar" %>
<div class="container-fluid" id="message-wrapper">
	<div id="message-form-container" class="container text-white">
		<div class="row">
			<div class="container-fluid mt-3 text-center">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %> 
      <% end %>
</div>
			<div id="form-column" class="col-md-5 mx-auto">
				<h1 class="text-center pb-5">Leave Us A message</h1>
				<%= simple_form_for(@message) do |f| %>
					<%= f.error_notification %>
					<%= f.input :name %>
					<%= f.input :email %>
					<%= f.input :phone_number %>
					<%= f.input :message %>					
					<%= f.button :submit, "message", id: "message-button" %>
				<% end %> 
			</div>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<%= render "layouts/navbar" %>

app/views/static_pages/home.html.erb
 <%= render "layouts/header" %>
<div class="container mb-5">
  <section id="mission-statement" class="offset">
    <div class="container">
        <div id="mission-group-icon-div" class="text-center mx-auto">
            <div class="mission-bars mission-bar-space d-inline-block"></div>
            <h6 class="pt-2">AYDF MISSION</h6>
            <div class="mission-bars mission-bar-space d-inline-block"></div>
        </div>
        
        <div id="our-mission-is">
            <h4 class="p-4 text-center">Our mission is to eat peoples money in cameroon and to embezle public funds</h4>
        </div>
    </div>
  </section>

  <section id="campaign" class="py-5">
    <h3 class="text-center">On going campaigns</h3>
    <div class="row">
      <% @campaigns.each do |campaign| %>
      <div class="col-9 col-sm-6 col-lg-4 mx-auto my-4">
        <div class="card">
          <%= link_to image_tag(campaign.photo, class: "card-img-top", alt: "picture"), campaign %>
          <div class="card-body">
            <div class="card-title">
              <h3 class="text-capitalize"><%= campaign.title %></h3>
              <h6>from <%= campaign.end_date.to_date.to_formatted_s :long_ordinal %> to the <%= campaign.end_date.to_date.to_formatted_s :long_ordinal %></h6>
            </div>
            <h4 class="primary-color text-capitalize"><%= truncate(campaign.content, :length => 50) %></h4>
          </div>
          <div class="card-footer team-icons d-flex justify-content-between">
            <a href=""><i class="fab fa-facebook fa-2x"></i></a>
            <%= link_to "Read More", campaign, class: "see-more-link h4" %>
            
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </section>

  <section id="reviews" class="py-5">
        <div id="slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
<!--               carousel item-->
                <div class="carousel-item active">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-10 mx-auto d-flex justify-content-between review-item py-3">
<!--                               image-->
                                <div class="align-self-center ml-3">
                                    <%= image_tag("photo-1548438294-1ad5d5f4f063.jpeg", class: "rounded-circle review-img", atl: "missing pic") %>
                                </div>
<!--                                text-->
                               <div class="review-text px-5">
                                   <h3 class="text-capitalize mb-3 primary-color">keep dreaming</h3>
                                   <div class="lead text-muted">lorem20 thid id hoe tlo kjfg jkjl; dfgj ;kjfg sdkfj</div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div> 
<!--                end of carousel item-->
<!--              carousel item-->
               <div class="carousel-item">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-10 mx-auto d-flex justify-content-between review-item py-3">
<!--                               image-->
                                <div class="align-self-center ml-3">
                                  
                                    <%= image_tag("photo-1543616991-75a2c125ff5b.jpeg", class: "rounded-circle review-img", atl: "missing pic") %>
                                </div>
<!--                                text-->
                               <div class="review-text px-5">
                                   <h3 class="text-capitalize mb-3 primary-color">keep dreaming</h3>
                                   <div class="lead text-muted">lorem20 thid id hoe tlo kjfg jkjl; dfgj ;kjfg sdkfj</div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
<!--                end of carousel item -->
           <!--              carousel item-->
               <div class="carousel-item">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-10 mx-auto d-flex justify-content-between review-item py-3">
<!--                               image-->
                                <div class="align-self-center ml-3">
                                    
                                    <%= image_tag("photo-1555580399-49e780f216b7.jpeg", class: "rounded-circle review-img", atl: "missing pic") %>
                                </div>
<!--                                text-->
                               <div class="review-text px-5">
                                   <h3 class="text-capitalize mb-3 primary-color">keep dreaming</h3>
                                   <div class="lead text-muted">lorem20 thid id hoe tlo kjfg jkjl; dfgj ;kjfg sdkfj</div>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
<!--                end of carousel item -->
            </div>
<!--            carousel controls-->
           <a href="#slider" class="carousel-control-prev" role="button" data-slide="prev">
               <span class="carousel-control-prev-icon"></span>
           </a>

           <a href="#slider" class="carousel-control-next" role="button" data-slide="next">
               <span class="carousel-control-next-icon"></span>
           </a>
        </div>
    </section>
</div>